name: Majunga.Libraries.Asl
trigger:
  branches:
    include:
    - '**/*'
    - '*'
  paths:
    include:
      - "AslPipeline.yml"
      - "Majunga.Libraries/Asl/*"
      
pool:
  name: "Default"

variables:
  - name: projectPath
    value: './Majunga.Libraries/Asl/Majunga.Libraries.Asl.csproj'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - group: nuget

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet build $(projectPath) /p:Configuration=Release --verbosity Detailed'

- task: PowerShell@2
  inputs:
    targetType: inline
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        script: 'dotnet pack $(projectPath)  --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'
    ${{ else }}:
        script: 'dotnet pack $(projectPath) --version-suffix $(Build.SourceBranchName)$(Build.BuildId) --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'

- task: PowerShell@2
  name: Push
  inputs:
    targetType: inline
    script: |
      $package = Get-ChildItem $(Build.ArtifactStagingDirectory)/*.nupkg
      dotnet nuget push "$package"  -s https://api.nuget.org/v3/index.json --api-key $(apikey) --skip-duplicate