name: Majunga.Libraries.RazorComponents

trigger:
  branches:
    include:
    - '**/*'
    - '*'
  paths:
    include:
      - "RazorComponentsPipeline.yml"
      - "RazorComponents/*"

pool:
  name: "Default"

variables:
  - name: projectPath
    value: './RazorComponents/Majunga.Libraries.RazorComponents.csproj'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - group: nuget

steps:
- task: PowerShell@2
  name: Build
  inputs:
    targetType: inline
    script: 'dotnet build $(projectPath) /p:Configuration=Release --verbosity Detailed'
- task: PowerShell@2
  name: Pack
  inputs:
    targetType: inline
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        script: 'dotnet pack $(projectPath) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'
    ${{ else }}:
        script: 'dotnet pack $(projectPath) --version-suffix $(Build.SourceBranchName)$(Build.BuildId) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'

- task: PowerShell@2
  name: Push
  inputs:
    targetType: inline
    script: |
      $package = Get-ChildItem $(Build.ArtifactStagingDirectory)/*.nupkg
      dotnet nuget push "$package.FullName"  -s https://api.nuget.org/v3/index.json --api-key $(apikey) --skip-duplicate