trigger:
  branches:
    include:
    - '*'

pool:
  name: "Default"

variables:
  - name: projectPath
    value: './RazorComponents/Majunga.Libraries.RazorComponents.csproj'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]


steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'write-host "isMain = $(isMain)"'
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet build $(projectPath) /p:Configuration=Release --verbosity Detailed'
- task: PowerShell@2
  inputs:
    targetType: inline
    ${{ if eq(variables['isMain'], 'false') }}:
        script: 'dotnet pack $(projectPath) --version-suffix $(Build.SourceBranchName)$(Build.BuildId) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'
    ${{ else }}:
        script: 'dotnet pack $(projectPath) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Majunga'
    allowPackageConflicts: true