trigger:
  branches:
    include:
    - '*'

pool:
  name: "Default"

variables:
  projectPath: './RazorComponents/Majunga.Libraries.RazorComponents.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  versionSuffix: ${{ if isMain}}:$(Build.SourceBranchName)$(Build.BuildId)

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet.exe build $(projectPath) /p:Configuration=Release --verbosity Detailed'
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet.exe pack $(projectPath) --version-suffix $(versionSuffix) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Majunga'
    allowPackageConflicts: true