trigger:
  branches:
    include:
    - '*'

pool:
  name: "Default"

variables:
  - name: projectPath
    value: './RazorComponents/Majunga.Libraries.RazorComponents.csproj'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: versionSuffix
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
        value: $(Build.SourceBranchName)$(Build.BuildId)
    ${{ else }}:
        value: ""

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet.exe build $(projectPath) /p:Configuration=Release --verbosity Detailed'
- task: PowerShell@2
  inputs:
    targetType: inline
    script: 'dotnet.exe pack $(projectPath) --version-suffix $(versionSuffix) --runtime browser-wasm --output $(Build.ArtifactStagingDirectory) /p:Configuration=Release --verbosity Detailed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Majunga'
    allowPackageConflicts: true